CREATE TABLE `usuarios` (
	`userId` INTEGER AUTO_INCREMENT NOT NULL,
	`userName` VARCHAR(100) NOT NULL,
	`userEmail` VARCHAR(100) NOT NULL,
	`userPassword` VARCHAR(255) NOT NULL,
	`userImg` VARCHAR(255) NULL,
	`userRole` VARCHAR(50) NOT NULL DEFAULT 'USER_ROLE',
	PRIMARY KEY(`userId`)
) ENGINE=INNODB;
